name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-format-validate:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate
